# Generated by Django 5.1.7 on 2025-03-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
    ]
